<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TarifasTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('tarifas')->insert([

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 1],
        	['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 1],
        	['tipo' => 'EEED', 'monto' => 200, 'id_zona' => 1],
        	['tipo' => 'NEX LOGÍSTICA', 'monto' => 450, 'id_zona' => 1],
        	['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 1],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 2],
        	['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 2],
        	['tipo' => 'EEED', 'monto' => 200, 'id_zona' => 2],
        	['tipo' => 'NEX LOGÍSTICA', 'monto' => 450, 'id_zona' => 2],
        	['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 2],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 3],
        	['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 3],
        	['tipo' => 'EEED', 'monto' => 200, 'id_zona' => 3],
        	['tipo' => 'NEX LOGÍSTICA', 'monto' => 450, 'id_zona' => 3],
        	['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 3],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 4],
        	['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 4],
        	['tipo' => 'EEED', 'monto' => 200, 'id_zona' => 4],
        	['tipo' => 'NEX LOGÍSTICA', 'monto' => 450, 'id_zona' => 4],
        	['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 4],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 5],
        	['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 5],
        	['tipo' => 'EEED', 'monto' => 200, 'id_zona' => 5],
        	['tipo' => 'NEX LOGÍSTICA', 'monto' => 450, 'id_zona' => 5],
        	['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 5],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 6],
        	['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 6],
        	['tipo' => 'EEED', 'monto' => 200, 'id_zona' => 6],
        	['tipo' => 'NEX LOGÍSTICA', 'monto' => 450, 'id_zona' => 6],
        	['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 6],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 7],
        	['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 7],
        	['tipo' => 'EEED', 'monto' => 200, 'id_zona' => 7],
        	['tipo' => 'NEX LOGÍSTICA', 'monto' => 450, 'id_zona' => 7],
        	['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 7],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 8],
        	['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 8],
        	['tipo' => 'EEED', 'monto' => 200, 'id_zona' => 8],
        	['tipo' => 'NEX LOGÍSTICA', 'monto' => 450, 'id_zona' => 8],
        	['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 8],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 9],
        	['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 9],
        	['tipo' => 'EEED', 'monto' => 200, 'id_zona' => 9],
        	['tipo' => 'NEX LOGÍSTICA', 'monto' => 450, 'id_zona' => 9],
        	['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 9],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 10],
        	['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 10],
        	['tipo' => 'EEED', 'monto' => 200, 'id_zona' => 10],
        	['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 10],
        	['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 10],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 11],
        	['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 11],
        	['tipo' => 'EEED', 'monto' => 200, 'id_zona' => 11],
        	['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 11],
        	['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 11],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 12],
        	['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 12],
        	['tipo' => 'EEED', 'monto' => 200, 'id_zona' => 12],
        	['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 12],
        	['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 12],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 13],
        	['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 13],
        	['tipo' => 'EEED', 'monto' => 200, 'id_zona' => 13],
        	['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 13],
        	['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 13],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 14],
        	['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 14],
        	['tipo' => 'EEED', 'monto' => 200, 'id_zona' => 14],
        	['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 14],
        	['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 14],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 15],
        	['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 15],
        	['tipo' => 'EEED', 'monto' => 200, 'id_zona' => 15],
        	['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 15],
        	['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 15],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 16],
        	['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 16],
        	['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 16],
        	['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 16],
        	['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 16],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 17],
        	['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 17],
        	['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 17],
        	['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 17],
        	['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 17],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 18],
        	['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 18],
        	['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 18],
        	['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 18],
        	['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 18],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 19],
        	['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 19],
        	['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 19],
        	['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 19],
        	['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 19],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 20],
        	['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 20],
        	['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 20],
        	['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 20],
        	['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 20],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 21],
        	['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 21],
        	['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 21],
        	['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 21],
        	['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 21],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 22],
        	['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 22],
        	['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 22],
        	['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 22],
        	['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 22],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 23],
        	['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 23],
        	['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 23],
        	['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 23],
        	['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 23],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 24],
        	['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 24],
        	['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 24],
        	['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 24],
        	['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 24],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 25],
        	['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 25],
        	['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 25],
        	['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 25],
        	['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 25],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 26],
        	['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 26],
        	['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 26],
        	['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 26],
        	['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 26],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 27],
        	['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 27],
        	['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 27],
        	['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 27],
        	['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 27],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 28],
        	['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 28],
        	['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 28],
        	['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 28],
        	['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 28],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 29],
        	['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 29],
        	['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 29],
        	['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 29],
        	['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 29],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 30],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 30],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 30],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 30],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 30],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 31],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 31],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 31],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 31],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 31],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 32],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 32],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 32],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 32],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 32],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 33],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 33],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 33],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 33],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 33],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 34],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 34],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 34],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 34],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 34],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 35],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 35],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 35],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 35],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 35],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 36],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 36],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 36],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 36],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 36],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 37],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 37],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 37],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 37],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 37],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 38],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 38],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 38],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 38],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 38],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 39],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 39],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 39],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 39],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 39],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 40],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 40],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 40],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 40],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 40],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 41],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 41],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 41],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 41],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 41],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 42],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 42],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 42],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 42],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 42],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 43],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 43],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 43],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 43],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 43],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 44],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 44],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 44],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 44],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 44],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 45],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 45],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 45],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 45],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 45],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 46],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 46],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 46],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 46],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 46],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 47],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 47],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 47],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 450, 'id_zona' => 47],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 47],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 48],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 48],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 48],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 450, 'id_zona' => 48],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 48],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 49],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 49],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 49],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 450, 'id_zona' => 49],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 49],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 50],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 50],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 50],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 450, 'id_zona' => 50],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 50],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 52],
			['tipo' => 'OESTE', 'monto' => 250, 'id_zona' => 52],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 52],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 52],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 52],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 53],
			['tipo' => 'OESTE', 'monto' => 250, 'id_zona' => 53],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 53],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 53],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 53],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 54],
			['tipo' => 'OESTE', 'monto' => 250, 'id_zona' => 54],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 54],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 54],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 54],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 55],
			['tipo' => 'OESTE', 'monto' => 250, 'id_zona' => 55],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 55],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 55],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 55],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 56],
			['tipo' => 'OESTE', 'monto' => 250, 'id_zona' => 56],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 56],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 56],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 56],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 57],
			['tipo' => 'OESTE', 'monto' => 250, 'id_zona' => 57],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 57],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 57],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 57],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 58],
			['tipo' => 'OESTE', 'monto' => 250, 'id_zona' => 58],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 58],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 58],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 58],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 59],
			['tipo' => 'OESTE', 'monto' => 250, 'id_zona' => 59],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 59],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 59],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 59],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 60],
			['tipo' => 'OESTE', 'monto' => 250, 'id_zona' => 60],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 60],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 60],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 60],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 61],
			['tipo' => 'OESTE', 'monto' => 250, 'id_zona' => 61],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 61],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 61],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 61],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 62],
			['tipo' => 'OESTE', 'monto' => 250, 'id_zona' => 62],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 62],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 62],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 62],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 63],
			['tipo' => 'OESTE', 'monto' => 250, 'id_zona' => 63],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 63],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 63],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 63],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 64],
			['tipo' => 'OESTE', 'monto' => 250, 'id_zona' => 64],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 64],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 64],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 64],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 65],
			['tipo' => 'OESTE', 'monto' => 250, 'id_zona' => 65],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 65],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 65],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 65],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 66],
			['tipo' => 'OESTE', 'monto' => 250, 'id_zona' => 66],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 66],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 66],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 66],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 67],
			['tipo' => 'OESTE', 'monto' => 250, 'id_zona' => 67],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 67],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 67],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 67],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 68],
			['tipo' => 'OESTE', 'monto' => 250, 'id_zona' => 68],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 68],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 68],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 68],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 69],
			['tipo' => 'OESTE', 'monto' => 250, 'id_zona' => 69],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 69],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 69],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 69],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 70],
			['tipo' => 'OESTE', 'monto' => 250, 'id_zona' => 70],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 70],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 70],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 70],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 71],
			['tipo' => 'OESTE', 'monto' => 250, 'id_zona' => 71],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 71],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 71],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 71],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 72],
			['tipo' => 'OESTE', 'monto' => 250, 'id_zona' => 72],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 72],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 72],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 72],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 73],
			['tipo' => 'OESTE', 'monto' => 250, 'id_zona' => 73],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 73],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 73],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 73],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 74],
			['tipo' => 'OESTE', 'monto' => 250, 'id_zona' => 74],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 74],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 74],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 74],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 75],
			['tipo' => 'OESTE', 'monto' => 250, 'id_zona' => 75],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 75],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 75],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 75],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 76],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 76],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 76],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 450, 'id_zona' => 76],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 76],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 77],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 77],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 77],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 450, 'id_zona' => 77],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 77],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 78],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 78],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 78],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 450, 'id_zona' => 78],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 78],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 79],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 79],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 79],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 450, 'id_zona' => 79],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 79],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 80],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 80],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 80],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 450, 'id_zona' => 80],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 80],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 81],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 81],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 81],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 450, 'id_zona' => 81],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 81],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 82],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 82],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 82],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 450, 'id_zona' => 82],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 82],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 83],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 83],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 83],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 83],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 83],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 84],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 84],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 84],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 84],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 84],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 85],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 85],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 85],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 85],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 85],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 86],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 86],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 86],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 86],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 86],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 87],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 87],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 87],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 87],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 87],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 88],
			['tipo' => 'OESTE', 'monto' => 500, 'id_zona' => 88],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 88],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 88],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 88],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 89],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 89],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 89],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 89],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 0, 'id_zona' => 89],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 90],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 90],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 90],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 90],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 0, 'id_zona' => 90],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 91],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 91],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 91],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 91],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 0, 'id_zona' => 91],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 92],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 92],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 92],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 92],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 0, 'id_zona' => 92],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 93],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 93],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 93],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 93],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 0, 'id_zona' => 93],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 94],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 94],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 94],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 94],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 0, 'id_zona' => 94],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 95],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 95],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 95],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 95],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 0, 'id_zona' => 95],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 96],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 96],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 96],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 96],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 0, 'id_zona' => 96],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 97],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 97],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 97],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 97],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 0, 'id_zona' => 97],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 98],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 98],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 98],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 98],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 0, 'id_zona' => 98],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 99],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 99],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 99],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 99],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 0, 'id_zona' => 99],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 100],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 100],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 100],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 100],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 0, 'id_zona' => 100],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 101],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 101],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 101],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 101],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 0, 'id_zona' => 101],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 102],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 102],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 102],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 102],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 0, 'id_zona' => 102],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 103],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 103],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 103],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 103],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 0, 'id_zona' => 103],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 104],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 104],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 104],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 104],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 0, 'id_zona' => 104],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 105],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 105],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 105],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 105],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 105],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 106],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 106],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 106],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 106],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 106],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 107],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 107],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 107],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 107],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 107],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 108],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 108],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 108],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 108],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 108],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 109],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 109],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 109],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 109],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 109],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 110],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 110],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 110],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 110],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 110],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 111],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 111],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 111],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 111],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 111],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 112],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 112],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 112],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 112],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 112],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 113],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 113],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 113],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 280, 'id_zona' => 113],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 113],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 114],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 114],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 114],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 450, 'id_zona' => 114],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 114],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 115],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 115],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 115],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 450, 'id_zona' => 115],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 115],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 116],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 116],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 116],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 450, 'id_zona' => 116],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 116],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 117],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 117],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 117],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 450, 'id_zona' => 117],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 117],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 118],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 118],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 118],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 450, 'id_zona' => 118],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 118],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 119],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 119],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 119],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 450, 'id_zona' => 119],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 119],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 120],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 120],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 120],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 450, 'id_zona' => 120],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 120],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 121],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 121],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 121],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 450, 'id_zona' => 121],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 121],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 122],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 122],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 122],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 450, 'id_zona' => 122],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 122],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 123],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 123],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 123],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 450, 'id_zona' => 123],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 123],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 124],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 124],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 124],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 450, 'id_zona' => 124],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 124],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 125],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 125],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 125],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 450, 'id_zona' => 125],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 125],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 126],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 126],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 126],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 450, 'id_zona' => 126],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 126],

        	['tipo' => 'FULLTRANS', 'monto' => 300, 'id_zona' => 127],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 127],
			['tipo' => 'EEED', 'monto' => 300, 'id_zona' => 127],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 450, 'id_zona' => 127],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 400, 'id_zona' => 127],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 128],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 128],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 128],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 128],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 128],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 129],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 129],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 129],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 129],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 129],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 130],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 130],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 130],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 130],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 130],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 131],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 131],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 131],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 131],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 131],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 132],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 132],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 132],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 132],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 132],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 133],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 133],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 133],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 133],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 133],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 134],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 134],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 134],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 134],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 134],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 135],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 135],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 135],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 135],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 135],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 136],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 136],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 136],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 136],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 136],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 137],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 137],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 137],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 137],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 137],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 138],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 138],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 138],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 138],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 138],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 139],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 139],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 139],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 139],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 139],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 140],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 140],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 140],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 140],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 140],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 141],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 141],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 141],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 141],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 141],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 142],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 142],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 142],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 142],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 142],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 143],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 143],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 143],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 143],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 143],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 144],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 144],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 144],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 144],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 144],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 145],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 145],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 145],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 145],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 145],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 146],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 146],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 146],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 146],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 146],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 147],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 147],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 147],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 147],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 147],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 148],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 148],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 148],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 148],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 148],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 149],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 149],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 149],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 149],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 149],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 150],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 150],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 150],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 150],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 150],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 151],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 151],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 151],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 151],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 151],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 152],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 152],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 152],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 152],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 152],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 153],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 153],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 153],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 153],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 153],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 154],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 154],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 154],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 154],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 154],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 155],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 155],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 155],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 155],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 155],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 156],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 156],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 156],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 156],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 156],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 157],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 157],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 157],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 157],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 157],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 158],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 158],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 158],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 158],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 158],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 159],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 159],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 159],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 159],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 159],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 160],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 160],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 160],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 160],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 160],

        	['tipo' => 'FULLTRANS', 'monto' => 450, 'id_zona' => 161],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 161],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 161],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 161],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 161],

        	['tipo' => 'FULLTRANS', 'monto' => 400, 'id_zona' => 162],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 162],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 162],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 162],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 162],

        	['tipo' => 'FULLTRANS', 'monto' => 400, 'id_zona' => 163],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 163],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 163],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 163],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 163],

        	['tipo' => 'FULLTRANS', 'monto' => 400, 'id_zona' => 164],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 164],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 164],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 164],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 164],

        	['tipo' => 'FULLTRANS', 'monto' => 400, 'id_zona' => 165],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 165],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 165],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 165],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 165],

        	['tipo' => 'FULLTRANS', 'monto' => 400, 'id_zona' => 166],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 166],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 166],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 166],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 166],

        	['tipo' => 'FULLTRANS', 'monto' => 400, 'id_zona' => 167],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 167],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 167],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 167],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 167],

        	['tipo' => 'FULLTRANS', 'monto' => 400, 'id_zona' => 168],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 168],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 168],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 168],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 168],

        	['tipo' => 'FULLTRANS', 'monto' => 400, 'id_zona' => 169],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 169],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 169],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 169],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 169],

        	['tipo' => 'FULLTRANS', 'monto' => 400, 'id_zona' => 170],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 170],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 170],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 170],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 170],

        	['tipo' => 'FULLTRANS', 'monto' => 400, 'id_zona' => 171],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 171],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 171],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 171],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 171],

        	['tipo' => 'FULLTRANS', 'monto' => 400, 'id_zona' => 172],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 172],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 172],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 172],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 172],

        	['tipo' => 'FULLTRANS', 'monto' => 400, 'id_zona' => 172],
			['tipo' => 'OESTE', 'monto' => 400, 'id_zona' => 172],
			['tipo' => 'EEED', 'monto' => 450, 'id_zona' => 172],
			['tipo' => 'NEX LOGÍSTICA', 'monto' => 610, 'id_zona' => 172],
			['tipo' => 'ENVÍOS FLEX', 'monto' => 510, 'id_zona' => 172],



        ]);
    }
}
